# -*- coding: utf-8 -*-
"""Empleo_Joven_Bogotá.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oaOAmz9FXPWEiKyCPhWrD1UGwoxue9w
"""

!pip install ipywidgets
from google.colab import output
output.enable_custom_widget_manager()
from IPython.display import display, Markdown

bienvenida = """
# 👋 Bienvenido a **Empleo Joven Bogotá**

🎯 *Transformación Digital del Empleo Juvenil: Una Herramienta Móvil para Bogotá*
Desarrollado por estudiantes de Ingeniería de Sistemas de la UNAD.

Este prototipo busca facilitar la inclusión laboral formal de jóvenes entre 18 y 28 años en Bogotá, conectándolos con vacantes que se ajusten a sus habilidades.
Una iniciativa académica impulsada por:

- Johan Manuel Santana Cortes
- Edison Fernando Cardenas Bermudez
- Danis Daniel Peniche Ospino

👨‍🏫 Tutor: Daniel Andrés Guzmán Arévalo
📚 Escuela de Ciencias Básicas, Tecnología e Ingeniería – UNAD
📅 Abril de 2025

---

💡 **A continuación podrás registrarte, seleccionar tus habilidades y recibir recomendaciones de empleo según tu perfil.**
"""

display(Markdown(bienvenida))

from datetime import datetime
from IPython.display import display, Markdown, clear_output
import ipywidgets as widgets

# --- Datos globales ---
usuarios = []
postulaciones = []

# --- Vacantes unificadas (33 + 5 = 38) ---
vacantes = [
    {"id": 1, "empresa": "TechBogotá", "titulo": "Desarrollador Junior", "ubicacion": "Bogotá", "experiencia_requerida": "0-1 años", "habilidades": ["Python", "Trabajo en equipo"], "educacion": "Tecnólogo o estudiante de últimos semestres"},
    {"id": 2, "empresa": "InnovaSoft", "titulo": "Asistente de Soporte Técnico", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Comunicación", "Resolución de problemas"], "educacion": "Bachiller o técnico"},
    {"id": 3, "empresa": "EcoData", "titulo": "Analista de Datos en Formación", "ubicacion": "Remoto", "experiencia_requerida": "Estudiante en práctica", "habilidades": ["Excel", "Power BI", "Python"], "educacion": "Estudiante de ingeniería o estadística"},
     {"id": 4, "empresa": "Datacy", "titulo": "Practicante de análisis de datos", "ubicacion": "Bogotá", "experiencia_requerida": "Sin experiencia", "habilidades": ["Excel", "Python", "SQL"], "educacion": "Estudiante de ingeniería o afines"},
    {"id": 5, "empresa": "RedFox Digital", "titulo": "Asistente de marketing digital", "ubicacion": "Bogotá", "experiencia_requerida": "0-1 año", "habilidades": ["Redes sociales", "Canva", "Google Ads"], "educacion": "Técnico o tecnólogo en mercadeo"},
    {"id": 6, "empresa": "Talento TI", "titulo": "Tester de software junior", "ubicacion": "Remoto", "experiencia_requerida": "Bootcamp o prácticas", "habilidades": ["Pruebas manuales", "Metodologías ágiles"], "educacion": "Tecnólogo en sistemas"},
    {"id": 7, "empresa": "Ecotienda App", "titulo": "Diseñador UI/UX en formación", "ubicacion": "Remoto", "experiencia_requerida": "No requerida", "habilidades": ["Figma", "Creatividad", "UX Writing"], "educacion": "Diseño o ingeniería multimedia"},
    {"id": 8, "empresa": "SoftGroup SAS", "titulo": "Soporte técnico nivel 1", "ubicacion": "Bogotá", "experiencia_requerida": "0-2 años", "habilidades": ["Atención al cliente", "Redes", "Ticketing"], "educacion": "Técnico en sistemas"},
    {"id": 9, "empresa": "Nubeco", "titulo": "Asistente de desarrollo front-end", "ubicacion": "Bogotá", "experiencia_requerida": "Bootcamp o formación práctica", "habilidades": ["HTML", "CSS", "JavaScript"], "educacion": "Tecnólogo en desarrollo web"},
    {"id": 10, "empresa": "EduNet", "titulo": "Auxiliar administrativo", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Excel", "Atención telefónica"], "educacion": "Técnico en administración"},
    {"id": 11, "empresa": "CívicaLab", "titulo": "Asistente de proyectos sociales", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Trabajo comunitario", "Organización"], "educacion": "Carreras sociales o humanísticas"},
    {"id": 12, "empresa": "TuringCode", "titulo": "Desarrollador móvil en formación", "ubicacion": "Remoto", "experiencia_requerida": "Estudiante de últimos semestres", "habilidades": ["Flutter", "Firebase"], "educacion": "Ingeniería de sistemas"},
    {"id": 13, "empresa": "Innobrand", "titulo": "Diseñador gráfico junior", "ubicacion": "Bogotá", "experiencia_requerida": "0-1 año", "habilidades": ["Photoshop", "Illustrator", "Creatividad"], "educacion": "Diseño gráfico"},
    {"id": 14, "empresa": "MediaConnect", "titulo": "Community Manager Junior", "ubicacion": "Bogotá", "experiencia_requerida": "0-1 año", "habilidades": ["Redes sociales", "Comunicación", "Canva"], "educacion": "Tecnología en comunicación o mercadeo"},
    {"id": 15, "empresa": "NextSoft", "titulo": "Desarrollador Backend Jr", "ubicacion": "Remoto", "experiencia_requerida": "Bootcamp o prácticas", "habilidades": ["Node.js", "MongoDB", "Git"], "educacion": "Ingeniería de sistemas o afines"},
    {"id": 16, "empresa": "SaludYa", "titulo": "Asistente administrativo en salud", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Atención al cliente", "Excel", "Facturación"], "educacion": "Técnico en administración o salud"},
    {"id": 17, "empresa": "CodeHouse", "titulo": "Frontend Intern", "ubicacion": "Remoto", "experiencia_requerida": "Estudiante activo", "habilidades": ["React", "HTML", "CSS"], "educacion": "Estudiante de ingeniería o diseño web"},
    {"id": 18, "empresa": "LogisticsPro", "titulo": "Auxiliar de bodega", "ubicacion": "Bogotá", "experiencia_requerida": "6 meses", "habilidades": ["Organización", "Trabajo físico", "Inventario"], "educacion": "Bachiller"},
    {"id": 19, "empresa": "LegalSoft", "titulo": "Digitador de documentos legales", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Digitación", "Ortografía", "Office"], "educacion": "Técnico administrativo o afines"},
    {"id": 20, "empresa": "Financiera Plus", "titulo": "Auxiliar contable junior", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Contabilidad básica", "Excel", "Normas NIIF"], "educacion": "Tecnólogo en contabilidad o finanzas"},
    {"id": 21, "empresa": "AgroTIC", "titulo": "Técnico en soporte de campo", "ubicacion": "Zona rural Cundinamarca", "experiencia_requerida": "1 año", "habilidades": ["GPS", "Instalación de sensores", "Movilidad"], "educacion": "Técnico electrónico o agrícola"},
    {"id": 22, "empresa": "RedDocentes", "titulo": "Monitor académico virtual", "ubicacion": "Remoto", "experiencia_requerida": "Estudiante o recién egresado", "habilidades": ["Tutorías", "Didáctica", "Manejo de plataformas"], "educacion": "Licenciatura o pedagogía"},
    {"id": 23, "empresa": "BioInnova", "titulo": "Asistente de laboratorio", "ubicacion": "Bogotá", "experiencia_requerida": "Prácticas universitarias", "habilidades": ["Manejo de muestras", "Normas de bioseguridad"], "educacion": "Estudiante de biología o química"},
    {"id": 24, "empresa": "GreenTech", "titulo": "Asistente de proyectos ambientales", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Excel", "Trabajo en campo", "Reportes"], "educacion": "Estudiante de ingeniería ambiental"},
    {"id": 25, "empresa": "AlphaTrans", "titulo": "Coordinador logístico junior", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Logística", "Rutas", "ERP"], "educacion": "Técnico o tecnólogo en logística"},
    {"id": 26, "empresa": "DataInsight", "titulo": "Junior Data Analyst", "ubicacion": "Remoto", "experiencia_requerida": "Bootcamp o certificación", "habilidades": ["Python", "Pandas", "Excel"], "educacion": "Ingeniería, matemáticas o afines"},
    {"id": 27, "empresa": "CineBogotá", "titulo": "Auxiliar de sala", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Atención al cliente", "Ventas", "Trabajo en equipo"], "educacion": "Bachiller"},
    {"id": 28, "empresa": "DocuScan", "titulo": "Escáner de documentos", "ubicacion": "Bogotá", "experiencia_requerida": "6 meses", "habilidades": ["Digitación", "Organización", "Office"], "educacion": "Técnico administrativo"},
    {"id": 29, "empresa": "AprendeYA", "titulo": "Tutor virtual de matemáticas", "ubicacion": "Remoto", "experiencia_requerida": "Estudiante universitario", "habilidades": ["Matemáticas", "Comunicación", "Didáctica"], "educacion": "Licenciatura o ingeniería"},
    {"id": 30, "empresa": "Televoz", "titulo": "Agente call center bilingüe", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Inglés", "Atención al cliente"], "educacion": "Bachiller o técnico"},
    {"id": 31, "empresa": "Artextil", "titulo": "Operario de confección", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Costura", "Manejo de máquinas"], "educacion": "Básica primaria"},
    {"id": 32, "empresa": "ByteWeb", "titulo": "Diseñador web trainee", "ubicacion": "Remoto", "experiencia_requerida": "Portafolio académico", "habilidades": ["HTML", "CSS", "Diseño responsive"], "educacion": "Diseño gráfico o desarrollo web"},
    {"id": 33, "empresa": "CulturArte", "titulo": "Gestor cultural auxiliar", "ubicacion": "Bogotá", "experiencia_requerida": "Voluntariado o prácticas", "habilidades": ["Organización de eventos", "Gestión cultural"], "educacion": "Ciencias sociales, artes o afines"},
    {"id": 34, "empresa": "MarketExpress", "titulo": "Repartidor urbano", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Moto", "Conocimiento de direcciones"], "educacion": "Bachiller"},
    {"id": 35, "empresa": "Superlimpio S.A.", "titulo": "Auxiliar de aseo", "ubicacion": "Bogotá", "experiencia_requerida": "6 meses", "habilidades": ["Limpieza", "Orden", "Puntualidad"], "educacion": "Bachiller"},
    {"id": 36, "empresa": "Tienda D1", "titulo": "Vendedor tienda a tienda", "ubicacion": "Bogotá", "experiencia_requerida": "1 año", "habilidades": ["Ventas", "Servicio al cliente"], "educacion": "Bachiller"},
    {"id": 37, "empresa": "TaxiYa", "titulo": "Conductor de taxi", "ubicacion": "Bogotá", "experiencia_requerida": "2 años", "habilidades": ["Licencia C1 o C2", "GPS", "Servicio"], "educacion": "Básica secundaria"},
    {"id": 38, "empresa": "LogiBodega", "titulo": "Auxiliar de bodega", "ubicacion": "Bogotá", "experiencia_requerida": "No requerida", "habilidades": ["Carga", "Inventario", "Trabajo físico"], "educacion": "Bachiller"},
]

# --- Widgets de la interfaz ---
habilidades_disponibles = sorted({h for vac in vacantes for h in vac["habilidades"]})
checkboxes = [widgets.Checkbox(value=False, description=h) for h in habilidades_disponibles]

nombre_txt = widgets.Text(placeholder="Tu nombre completo", description="👤 Nombre:")
correo_txt = widgets.Text(placeholder="Correo electrónico", description="📧 Correo:")
celular_txt = widgets.Text(placeholder="Número de celular", description="📱 Celular:")
ciudad_txt = widgets.Text(placeholder="Ciudad", description="📍 Ciudad:")
formacion_txt = widgets.Text(placeholder="Formación académica", description="🎓 Formación:")
boton_confirmar = widgets.Button(description="Registrarse y ver vacantes")

vacantes_dropdown = widgets.Dropdown(options=[], description="📌 Vacante:")
boton_postular = widgets.Button(description="✅ Postularme")

# --- Funciones del sistema ---
def registrar_usuario(nombre, correo, celular, ciudad, formacion, habilidades):
    usuario = {
        "id": len(usuarios) + 1,
        "nombre": nombre,
        "correo": correo,
        "celular": celular,
        "ciudad": ciudad,
        "formacion": formacion,
        "habilidades": habilidades,
        "fecha_registro": datetime.now().isoformat()
    }
    usuarios.append(usuario)
    display(Markdown(f"✅ **Usuario registrado:** `{nombre}`"))
    return usuario["id"]

def postular(usuario_id, vacante_id):
    postulaciones.append({
        "usuario_id": usuario_id,
        "vacante_id": vacante_id,
        "fecha_postulacion": datetime.now().isoformat()
    })
    u = next(u for u in usuarios if u["id"] == usuario_id)
    v = next(v for v in vacantes if v["id"] == vacante_id)
    display(Markdown(f"📨 `{u['nombre']}` se ha postulado a `{v['titulo']}` en **{v['empresa']}**.\n📱 Se contactará al número: `{u['celular']}`"))

def postular_con_dropdown(b):
    vacante_id = vacantes_dropdown.value
    if vacante_id:
        postular(usuario_id_global, vacante_id)
    else:
        display(Markdown("❌ No has seleccionado una vacante."))

boton_postular.on_click(postular_con_dropdown)

def cuando_confirma(b):
    clear_output()
    seleccionadas = [cb.description for cb in checkboxes if cb.value]
    nombre = nombre_txt.value.strip()
    correo = correo_txt.value.strip()
    celular = celular_txt.value.strip()
    ciudad = ciudad_txt.value.strip()
    formacion = formacion_txt.value.strip()

    if not nombre or not correo or not celular:
        display(Markdown("❌ **Por favor completa todos los campos obligatorios.**"))
        return

    global usuario_id_global
    usuario_id_global = registrar_usuario(nombre, correo, celular, ciudad, formacion, seleccionadas)

    usuario = next(u for u in usuarios if u["id"] == usuario_id_global)
    habilidades_usuario = set(usuario["habilidades"])
    recomendaciones = [v for v in vacantes if habilidades_usuario.intersection(set(v["habilidades"]))]

    if recomendaciones:
        display(Markdown(f"🎯 **Vacantes recomendadas para `{usuario['nombre']}`:**"))
        opciones = []
        for vac in recomendaciones:
            opciones.append((f"{vac['titulo']} en {vac['empresa']} ({vac['ubicacion']})", vac["id"]))
            print(f"[{vac['id']}] {vac['titulo']} en {vac['empresa']} ({vac['ubicacion']})")
            print(f"   ➤ Requisitos: {vac['experiencia_requerida']} | Educación: {vac['educacion']}")
            print(f"   ➤ Habilidades clave: {', '.join(vac['habilidades'])}\n")

        vacantes_dropdown.options = opciones
        display(Markdown("### ✍️ Elige una vacante y haz clic en 'Postularme':"))
        display(vacantes_dropdown)
        display(boton_postular)
    else:
        display(Markdown("⚠️ No se encontraron vacantes compatibles con tu perfil."))

boton_confirmar.on_click(cuando_confirma)

# --- Interfaz principal ---
display(Markdown("## 🧾 Completa tus datos personales"))
display(nombre_txt, correo_txt, celular_txt, ciudad_txt, formacion_txt)

display(Markdown("## 💼 Selecciona tus habilidades:"))
for cb in checkboxes:
    display(cb)

display(boton_confirmar)